Implement getToken callable
Instant-Visio/InstantVisio-WebApp pull request #292
Opened 2020-11-26 21:03 UTC by HugoGresse

2020-11-27 08:33 UTC, MattiaPrimavera requested changes

2020-11-27 08:33 UTC, MattiaPrimavera commented on functions/src/db/getUserToken.ts
> +        return null
for every created user, a token should normally exist. If it does not, I would say it is an error case

2020-11-27 08:33 UTC, MattiaPrimavera commented on functions/src/db/getUserToken.ts
> +    return null
this as well seems to me a *No valid token found* error

2020-11-27 08:33 UTC, MattiaPrimavera commented on functions/src/db/getUserToken.ts
> +    return null
if this correctly returns `null`, then `getToken` as well would send back `null` to the client side, I guess

2020-11-28 13:44 UTC, HugoGresse commented
I need this for another PR, comments/review here will still be managed but in another PR.

2020-11-28 13:45 UTC, merged